openapi: 3.2.0
info:
  title: Great American Insurance - Risk Assessment Experience…
  version: 1.0.0
tags:
- name: experienceModification
paths:
  /api/experienceModification:
    post:
      tags:
      - experienceModification
      responses:
        '200':
          description: OK
      summary: Create api experience modification
      x-summary-source: derived
      operationId: postApiExperienceModification
      x-operation-id-source: derived
