openapi: 3.2.0
info:
  title: Great American Insurance - Opportunity Update API
  version: 1.0.0
tags:
- name: Update
paths:
  /api/update:
    post:
      tags:
      - Update
      responses:
        '200':
          description: OK
      summary: Create api update
      x-summary-source: derived
      operationId: postApiUpdate
      x-operation-id-source: derived
