openapi: 3.2.0
info:
  title: Great American Insurance Contract API
  version: 1.0.0
tags:
- name: Contract
paths:
  /api/contract:
    post:
      tags:
      - Contract
      responses:
        '200':
          description: OK
      summary: Create api contract
      x-summary-source: derived
      operationId: postApiContract
      x-operation-id-source: derived
