openapi: 3.2.0
info:
  title: Great American Insurance - Ingestion Ingest API
  version: 0.187.0
tags:
- name: Ingest
paths:
  /api/ingest:
    post:
      responses:
        '200':
          description: OK
      tags:
      - Ingest
      summary: Create api ingest
      x-summary-source: derived
      operationId: postApiIngest
      x-operation-id-source: derived
