openapi: 3.2.0
info:
  title: Great American Insurance - Risk Assessment Moratorium API
  version: 1.0.0
tags:
- name: moratorium
paths:
  /api/moratorium:
    post:
      tags:
      - moratorium
      responses:
        '200':
          description: OK
      summary: Create api moratorium
      x-summary-source: derived
      operationId: postApiMoratorium
      x-operation-id-source: derived
